import { BaseAgent } from "./core/agentCore.js";
import { agentInstructions } from "./instructions/softwareArchitectInstructions.js";
import { nodeTools, toolHandlers } from "./tools/nodeDeveloperTools.js"; // Reusing FS tools
import { baToolHandlers } from "./tools/baTools.js"; // Reusing assignTask

class SoftwareArchitectAgent extends BaseAgent {

	async executeReasoning(payload) {
		const chat = this.model.startChat({
			tools: [{ functionDeclarations: this.tools }]
		});

		// The Architect reads the PRD generated by the BA
		const context = `
			Design Request from BA: ${payload.instruction}
			Location of PRD: ${payload.prdPath || "Check the workspace directory."}
		`;

		const result = await chat.sendMessage(context);
		const call = result.response.candidates[0].content.parts.find(parts => parts.functionCall);

		if (call) {
			const { name, args } = call.functionCall;
			
			// Handle the generic tools
			let toolResult;
			if (name === "assignTask") {
				toolResult = await baToolHandlers.assignTask(args);
			} else {
				toolResult = await toolHandlers[name](args);
			}
			
			return toolResult.message;
		}

		return result.response.text();
	}

}

const agent = new SoftwareArchitectAgent("Software Architect", agentInstructions, nodeTools);
agent.initialize();
