import { BaseAgent } from "./agentCore.js";
import { agentInstructions } from "./instructions/softwareArchitectInstructions.js";
import { commonTools, commonToolHandlers } from "./tools/common.js";

class SoftwareArchitectAgent extends BaseAgent {

	async executeReasoning(payload) {
		const taskId = payload.taskId;
		const projectName = payload.metadata?.projectName || "default-project";

		const chat = this.model.startChat({
			tools: [{ functionDeclarations: this.tools }]
		});

		await this.log(taskId, "info", `Starting software architecture design for project: ${projectName}`, { instruction: payload.instruction });

		// The Architect reads the PRD generated by the BA
		const context = `
			Project Name: ${projectName}
			Design Request from BA: ${payload.instruction}
		`;

		await this.log(taskId, "info", "Software Architect Reasoning Loop Started");

		let message = context;
		let isComplete = false;
		let finalResponse = "";

		while (!isComplete) {
			try {
				const result = await chat.sendMessage(message);
				const response = result.response;

				let text = "";
				try {
					text = response.text();
				} catch (e) {
					// text() throws if content is undefined
				}

				if (text && text.trim()) {
					await this.log(taskId, "info", "Software Architect Reasoning Output", { text });
				}

				const call = response.candidates?.[0]?.content?.parts?.find(parts => parts.functionCall);

				if (call) {
					const { name, args } = call.functionCall;
					await this.log(taskId, "debug", `Architect Executing Tool: ${name}`, { args });
					
					const toolResult = await commonToolHandlers[name]({
						...args,
						taskId,
						projectName,
						metadata: payload.metadata
					});

					await this.log(taskId, "debug", `Architect Tool Result: ${name}`, { toolResult });
					
					message = [{ functionResponse: { name, response: toolResult } }];
				} else {
					finalResponse = text || "Software Architecture Design Complete.";
					isComplete = true;
				}
			} catch (error) {
				await this.log(taskId, "error", "Error during Software Architect reasoning loop", { error: error.message });
				return `Error: ${error.message}`;
			}
		}

		return finalResponse;
	}

}

const agent = new SoftwareArchitectAgent("Software Architect", agentInstructions, commonTools);
agent.initialize();
