import { BaseAgent } from "./agentCore.js";
import { agentInstructions } from "./instructions/softwareArchitectInstructions.js";
import { commonTools, commonToolHandlers } from "./tools/common.js";

class SoftwareArchitectAgent extends BaseAgent {

	async executeReasoning(payload) {
		const chat = this.model.startChat({
			tools: [{ functionDeclarations: this.tools }]
		});

		// The Architect reads the PRD generated by the BA
		const context = `
			Design Request from BA: ${payload.instruction}
			Location of PRD: ${payload.prdPath || "Check the workspace directory."}
		`;

		const result = await chat.sendMessage(context);
		const call = result.response.candidates[0].content.parts.find(parts => parts.functionCall);

		if (call) {
			const { name, args } = call.functionCall;
			
			// Handle the generic tools
			const toolResult = await commonToolHandlers[name](args);
			
			return toolResult.message || toolResult.status;
		}

		return result.response.text();
	}

}

const agent = new SoftwareArchitectAgent("Software Architect", agentInstructions, commonTools);
agent.initialize();
