import fs from "fs/promises";
import path from "path";
import { GoogleGenAI } from "@google/genai";
import { config } from "../config.js";

export const designerTools = [
	{
		name: "generateMockup",
		description: "Generates an image mockup based on a visual prompt and saves it to the project directory.",
		parameters: {
			type: "object",
			properties: {
				visualPrompt: { type: "string", description: "Detailed descriptive prompt for the image generation model." },
				projectName: { type: "string" },
				artifactName: { type: "string", description: "Filename for the mockup (e.g., 'main-ui-mockup')" }
			},
			required: ["visualPrompt", "projectName", "artifactName"]
		}
	}
];

export const designerToolHandlers = {
	generateMockup: async ({ visualPrompt, projectName, artifactName }) => {
		const genAI = new GoogleGenAI(config.ai.key);
		
		try {
			// Using Imagen model for generation
			const model = genAI.getGenerativeModel({ model: "imagen-3.0-generate-001" });

			const result = await model.generateImages({
				prompt: visualPrompt,
				numberOfImages: 1,
				safetySettings: [
					{
						category: "HARM_CATEGORY_HARASSMENT",
						threshold: "BLOCK_MEDIUM_AND_ABOVE",
					},
				],
			});

			if (!result.images || result.images.length === 0) {
				return { status: "error", message: "No image was generated by the model." };
			}

			const baseDir = `${config.paths.projects}/${projectName}/mockups`;
			await fs.mkdir(baseDir, { recursive: true });

			const filePath = path.join(baseDir, `${artifactName}.png`);
			const imageBuffer = Buffer.from(result.images[0].base64, "base64");
			
			await fs.writeFile(filePath, imageBuffer);

			return { 
				status: "success", 
				message: `Mockup generated and saved to ${filePath}`,
				path: filePath
			};
		} catch (error) {
			console.error("Image Generation Error:", error);
			return { status: "error", message: `Failed to generate mockup: ${error.message}` };
		}
	}
};
